### PR TITLE
Sample Unit tests For YourContract.sol

### PR DESCRIPTION
**Pull request by ValentineCodes**
## Description

Added a sample unit test for YourContract.sol

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

Your ENS/address:
valentineorga.eth

@cacosta88

### CODE REVIEW

**Comment by cacosta88** [comment]
reopening pr

**Comment by cacosta88** [comment]
@ValentineCodes Thanks for putting this test file together, this is an awesome learning experience for me! Also thanks for the changes that involve spacing, indentation, line breaks, and similar formatting adjustments in the contract as well. Next time if you could please separate these types of changes from functional changes (from my review your only functional change was changing the MAXCREATOR from 25 to 2, please correct me if I am wrong) when making commits and submitting for code review--This makes it easier for the reviewer to distinguish between changes that affect the functionality of the code and those that are purely stylistic. I reviewed the stylistic changes in the contract line-by-line and they look great! Thanks again!

**Comment by ValentineCodes** [comment]
Got it!👌🏽... Glad to help!

**Comment by ValentineCodes** [comment]
Got it!👌🏽

**Comment by ValentineCodes** [comment]
Got it!👌🏽

**Pull request merged**
